version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # registries:
    #   - github-octocat

# registries:
#   github-octocat:
#     type: git
#     url: https://github.com
#     username: x-access-token
#     password: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
